### PR TITLE
Allow shorthand

### PR DESCRIPTION
**Pull request by Genimelineji**
Added option to disable attribute shorthand when formatting code. Also changed readme.md

### CODE REVIEW

**Comment by UnwrittenFun** [comment]
Looks good thanks!

If you've got some time would you be able to add tests? If not no worries, it'll just take a little longer to get in as I don't have much time atm to do it myself.

To test with options, create a new printer test with the expected output when the option is enabled, then create an options file alongside it.
Example:
https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/0debb22edc1a1eb49c5925f9f5a133d35ffdf0b7/test/printer/samples/self-closing-tags.html#L1
https://github.com/UnwrittenFun/prettier-plugin-svelte/blob/0debb22edc1a1eb49c5925f9f5a133d35ffdf0b7/test/printer/samples/self-closing-tags.options.json#L1-L3

**Comment by Genimelineji** [comment]
No problem. i'll look into it.

**Comment by Genimelineji** [comment]
Added test, Everything is ok.

**Comment by UnwrittenFun** [comment]
Sorry, your update must have slipped past me, looks good thanks!

**Pull request merged**
