### PR TITLE
Fixes #29

### LINKED ISSUE #29: HTML entities not preserved
HTML entities in templates are replaced with their literal equivalents. For example

```
5 &lt; 6
```

is transformed into
```
5 < 6
```

This can cause encoding issues with unicode entities and compile errors with `<` and `>`.

### PR DESCRIPTION
**Pull request by RedHatter**
This will fix #29 when sveltejs/svelte#2859 lands.

### CODE REVIEW

**Comment by RedHatter** [comment]
As per the linked PR now exclusively uses `raw` for text nodes.

**Comment by UnwrittenFun** [comment]
we're going to have to bump the required version of svelte if relying solely on `.raw`

**Comment by RedHatter** [comment]
Right, I didn't think of that. I'll revert.

**Comment by UnwrittenFun** [comment]
Looks good, thanks!

**Pull request merged**
